/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.88
 * Generated at: 2018-09-20 20:21:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\t<title>HOME AUTOMATION</title>\n");
      out.write("\t<link rel=\"shortcut icon\" type=\"image/png\" href=\"title.png\"/>\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("\t<style type=\"text/css\">\n");
      out.write("\n");
      out.write("\t\t.footer {\n");
      out.write("\t\t\tposition: fixed;\n");
      out.write("\t\t\tleft: 0;\n");
      out.write("\t\t\tbottom: 0;\n");
      out.write("\t\t\twidth: 100%;\n");
      out.write("\t\t\theight: 2em;\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t#company_box{font-size: 1em;background-color: #000a !important;}\n");
      out.write("\t\t#company_initial{color: #fff;}\n");
      out.write("\t\t#company_text{color: #08AA0F;}\n");
      out.write("\t\t#company_name{color: #03A9F4;}\n");
      out.write("\n");
      out.write("\t\tbody{\n");
      out.write("\t\t\tbackground:#ccc url('http://www.a1concept.com/wp-content/uploads/2018/03/Fabulous-By-Office-Room-About-Office-Room.jpg') center center/cover no-repeat fixed;\n");
      out.write("\t\t\t  -webkit-background-size: cover;\n");
      out.write("\t\t\t-moz-background-size: cover;\n");
      out.write("\t\t\t  -o-background-size: cover;\n");
      out.write("\t\t\t  background-size: cover;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t.btn-circle.btn-xl {\n");
      out.write("\t\t    width: 50px;\n");
      out.write("\t\t    height: 50px;\n");
      out.write("\t\t    padding: 10px;\n");
      out.write("\t\t    border-radius: 35px;\n");
      out.write("\t\t    font-size: 24px;\n");
      out.write("\t\t    line-height: 1.33;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");

response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); // HTTP 1.1.
response.setHeader("Pragma", "no-cache"); // HTTP 1.0.
response.setHeader("Expires", "0");
response.setDateHeader("Expires", -1);

if(	session.getAttribute("mobile")  == null && session.getAttribute("pass") == null){
	
	response.sendRedirect("index.jsp");
}


      out.write("\n");
      out.write("\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\n");
      out.write("\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\"><i class=\"fa fa-home fa-lg\"></i> HOME AUTOMATION</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<form method=\"POST\" action=\"logoutprocess.jsp\">\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\" name=\"logout\" style=\"margin: .5em;\"><i class=\"fa fa-sign-out fa-md\"></i> Logout </button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav> \n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"alert alert-success text-center\" id=\"alert_success\" style=\"display: none;\"></div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"alert alert-danger text-center\" id=\"alert_dev_id_danger\" style=\"display: none;\"></div>\n");
      out.write("\t\t<br>\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t<div class=\"panel panel-danger text-center\">\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\"><h3>CONTROL </h3>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"create_device\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Add Device\" style=\"float: right;\" class=\"btn btn-info btn-circle btn-xl\"><i class=\"fa fa-plus fa-lg\"></i></button><br>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<div id=\"dev_add\" style=\"display: none;\">\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" >\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group \">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"dev_name\"  placeholder=\"Enter Device Name\" autocomplete=\"off\" required>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" name=\"dev_submit\" class=\"btn btn-success mb-2\">Add Device</button>\n");
      out.write("\t\t\t\t\t\t\t</form><br>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" id=\"cancel\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Cancel\" class=\"btn btn-danger btn-sm\"><i class=\"fa fa-times\"></i></button>\n");
      out.write("\t\t\t\t\t\t\t<br><br>\n");
      out.write("\t\t\t<div class=\"alert alert-success text-center\" role=\"alert\">\n");
      out.write("\t\t\t\t<strong>Lamp1 Device Created.</strong>\n");
      out.write("\t\t\t</div>\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div id=\"dev_select\">\n");
      out.write("\t\t\t\t\t\t\t<label> <i class=\"fa fa-lightbulb-o fa-lg\" style=\"color: #FFA000;\"></i> Device:</label><br>\n");
      out.write("\t\t\t\t\t\t\t<select id=\"device_name\" name=\"device_name\" style=\"width: 20em;\" required >\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">-- Select Device --</option>\n");
      out.write("\t\t\t\t\t\t\t<!-- jquery -->\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<label><i class=\"fa fa-power-off fa-lg\" style=\"color: #E64A19;\"></i> Power:</label><br>\n");
      out.write("\t\t\t\t\t\t\t<select id=\"ctrl_power\" style=\"width: 20em;\">\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">-- Select Power --</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"on\">ON</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"off\">OFF</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<br><br>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"alert alert-success text-center\" id=\"alert_success\" style=\"display: none;\"></div>\n");
      out.write("\t\t\t\t<div class=\"alert alert-danger text-center\" id=\"alert_dev_id_danger\" style=\"display: none;\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-sm-6\" style=\"padding-left: 5em;\">\n");
      out.write("\t\t\t\t<div class=\"panel panel-warning\">\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading text-center\"><h3>STATUS</h3></div>\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading text-center\"><b style=\"float: left;\">Device</b> | <b style=\"float: right;\">Status</b></div>\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div id=\"status_group\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-cogs fa-lg\" style=\"color: #795548;\"></i> &nbsp;Light1: </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\"><span class=\"label label-success\" style=\"float: right; font-size: 1.2em;\">On</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div><br><div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-cogs fa-lg\" style=\"color: #795548;\"></i> &nbsp;Light2: </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\"><span class=\"label label-success\" style=\"float: right; font-size: 1.2em;\">On</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div><br><div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-cogs fa-lg\" style=\"color: #795548;\"></i> &nbsp;Fan1: </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\"><span class=\"label label-warning\" style=\"float: right; font-size: 1.2em;\"\">Off</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div><br><div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-cogs fa-lg\" style=\"color: #795548;\"></i> &nbsp;Light3: </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\"><span class=\"label label-warning\" style=\"float: right; font-size: 1.2em;\"\">Off</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div><br><div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-cogs fa-lg\" style=\"color: #795548;\"></i> &nbsp;Dev_2: </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\"><span class=\"label label-warning\" style=\"float: right; font-size: 1.2em;\"\">Off</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div><br><div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-cogs fa-lg\" style=\"color: #795548;\"></i> &nbsp;Ravi: </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\"><span class=\"label label-warning\" style=\"float: right; font-size: 1.2em;\"\">Off</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div><br><div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-cogs fa-lg\" style=\"color: #795548;\"></i> &nbsp;L2: </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\"><span class=\"label label-warning\" style=\"float: right; font-size: 1.2em;\"\">Off</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div><br><div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-cogs fa-lg\" style=\"color: #795548;\"></i> &nbsp;L2: </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\"><span class=\"label label-warning\" style=\"float: right; font-size: 1.2em;\"\">Off</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div><br><div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-cogs fa-lg\" style=\"color: #795548;\"></i> &nbsp;Laml: </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\"><span class=\"label label-warning\" style=\"float: right; font-size: 1.2em;\"\">Off</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div><br><div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-cogs fa-lg\" style=\"color: #795548;\"></i> &nbsp;Lamp1: </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\"><span class=\"label label-warning\" style=\"float: right; font-size: 1.2em;\"\">Off</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div><br><div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-cogs fa-lg\" style=\"color: #795548;\"></i> &nbsp;Lamp1: </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\"><span class=\"label label-warning\" style=\"float: right; font-size: 1.2em;\"\">Off</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div><br>\n");
      out.write("\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-thermometer-three-quarters fa-lg\" style=\"color: #8BC34A;\"></i>\n");
      out.write(" \t\t\t\t\t\t\t\t\tTemperature : &nbsp; <span class=\"label label-info\" style=\"float: right; font-size: 1.2em;\"> 27&deg;C</span>\n");
      out.write(" \t\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t\t\t\t\t<label style=\"float: left;\"><i class=\"fa fa-tint fa-lg\" style=\"color: #0288D1;\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\tHumidity : &nbsp; <span class=\"label label-info\" style=\"float: right; font-size: 1.2em;\">60 %</span>\n");
      out.write("\t\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("<footer class=\"footer\">\n");
      out.write("\t<div class=\"row text-center\">\n");
      out.write("\t<div class=\"col-md-12\">\n");
      out.write("\t\t<p class=\"label label-block label-default\" id=\"company_box\">\n");
      out.write("\t\t\t<span id=\"company_initial\">Powered By</span>\n");
      out.write("\t\t\t<a href=\"http://os3infotech.com\" target=\"_blank\">\n");
      out.write("\t\t\t\t<b id=\"company_text\">OS3</b>\n");
      out.write("\t\t\t\t<b id=\"company_name\"> Infotech Pvt. Ltd.</b>\n");
      out.write("\t\t\t</a>\n");
      out.write("\t\t</p>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\n");
      out.write("\t\tvar interval;\n");
      out.write("\t\tinterval = setInterval(function(){\n");
      out.write("\t\t\t$(\"#status_group\").load(location.href + \" #status_group\")}, 5000);\n");
      out.write("\n");
      out.write("\t\t\t$('[data-toggle=\"tooltip\"]').tooltip();\n");
      out.write("\n");
      out.write("\t\t\t$(\"#create_device\").click(function(){\n");
      out.write("\t\t\t$(\"#dev_add\").show();\n");
      out.write("\t\t\t$(\"#dev_select\").hide();\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$(\"#cancel\").click(function(){\n");
      out.write("\t\t\t$(\"#dev_add\").hide();\n");
      out.write("\t\t\t$(\"#dev_select\").show();\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("//////control power on change...\n");
      out.write("$(\"#ctrl_power\").on('change', function() {\n");
      out.write("\n");
      out.write("\tvar device_name = $( \"#device_name\" ).val();\n");
      out.write("\tvar ctrl_power = $(\"#ctrl_power\").val();\n");
      out.write("\tvar json =JSON.stringify({deviceName:device_name, control:ctrl_power});\n");
      out.write("\tconsole.log(json);\n");
      out.write("\n");
      out.write("\tif (device_name == \"\") {\n");
      out.write("\t\t$( \"#alert_dev_id_danger\" ).fadeTo(500, 1);\n");
      out.write("\t\t$( \"#alert_dev_id_danger\" ).html(\"<strong>Select device before proceeding</strong>\");\n");
      out.write("\t\t$( \"#alert_dev_id_danger\" ).fadeTo(4000, 600).hide(600);\n");
      out.write("\t}else if (ctrl_power == \"\") {\n");
      out.write("\t\t$( \"#alert_dev_id_danger\" ).fadeTo(500, 1);\n");
      out.write("\t\t$( \"#alert_dev_id_danger\" ).html(\"<strong>Select Power before proceeding</strong>\");\n");
      out.write("\t\t$( \"#alert_dev_id_danger\" ).fadeTo(4000, 600).hide(600);\n");
      out.write("\t}else {\n");
      out.write("\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl : \"setcontrol\",\n");
      out.write("\t\t\ttype: 'POST',\n");
      out.write("\t\t\tdataType : 'JSON',\n");
      out.write("\t\t\tdata :json ,\n");
      out.write("\t\t\tsuccess: function(res){\n");
      out.write("\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\tif (res.st == 1) {\n");
      out.write("\t\t\t\t\t$(\"#alert_dev_id_danger\").hide();\n");
      out.write("\t\t\t\t\t$( \"#alert_success\" ).fadeTo(500, 1);\n");
      out.write("\t\t\t\t\t$( \"#alert_success\" ).html(\"<strong>\"+ device_name.toUpperCase() +\"</strong> is Successfully set control <strong>\" + ctrl_power.toUpperCase() + \"</strong>\");\n");
      out.write("\t\t\t\t\t$(\"#alert_success\").fadeTo(4000, 600).hide(600);\n");
      out.write("\t\t\t\t}\telse if (res.st == 2) {\n");
      out.write("\t\t\t\t\t$( \"#alert_dev_id_danger\" ).fadeTo(500, 1);\n");
      out.write("\t\t\t\t\t$( \"#alert_dev_id_danger\" ).html(\"<strong>Technical Error:</strong> Invalid Device selected\");\n");
      out.write("\t\t\t\t\t$(\"#alert_dev_id_danger\").fadeTo(4000, 600).hide(600);\n");
      out.write("\t\t\t\t}else if (res.st == 3) {\n");
      out.write("\t\t\t\t\t$( \"#alert_dev_id_danger\" ).fadeTo(500, 1);\n");
      out.write("\t\t\t\t\t$( \"#alert_dev_id_danger\" ).html(\"<strong>\"+ device_name.toUpperCase() +\"</strong> is Already set control <strong>\" + ctrl_power.toUpperCase() + \"</strong>\");\n");
      out.write("\t\t\t\t\t$(\"#alert_dev_id_danger\").fadeTo(4000, 600).hide(600);\n");
      out.write("\t\t\t\t}\t\t\t\t\n");
      out.write("\t\t\t},\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("\n");
      out.write("/*  get list */\n");
      out.write("\n");
      out.write("\t$(\"#device_name\").click(function(){\n");
      out.write("\t\tvar list=\"\";\n");
      out.write("\t\t\n");
      out.write("\t\t$.get(\"getlist\",function(data ,status){\n");
      out.write("\t\t\t var $select = $(\"#device_name\");\n");
      out.write("             $select.find(\"option\").remove(); \n");
      out.write("\t\t\t$.each( JSON.parse(data), function(key,value){\n");
      out.write("\t\t\t\tconsole.log(key + \" : \"+ value);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t list = \"<option  value=\"+ value+\">\"+value+\"</option>\";\t\t\n");
      out.write("\t\t\t\t $(\"#device_name\").append(list);\n");
      out.write("\t\t\t\t list=\"\";\n");
      out.write("\t\t\t}); \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("/* end list  */\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
